const ERROR_CODES = {
    // Authentication & Authorization
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INVALID_TOKEN: 'INVALID_TOKEN',

    // User related
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

    // Book related
    BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
    BOOK_ALREADY_EXISTS: 'BOOK_ALREADY_EXISTS',

    // Post related
    POST_NOT_FOUND: 'POST_NOT_FOUND',
    POST_ACCESS_DENIED: 'POST_ACCESS_DENIED',

    // Comment related
    COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
    COMMENT_ACCESS_DENIED: 'COMMENT_ACCESS_DENIED',

    // Favorite related
    FAVORITE_ALREADY_EXISTS: 'FAVORITE_ALREADY_EXISTS',
    FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',

    // Follow related
    FOLLOW_ALREADY_EXISTS: 'FOLLOW_ALREADY_EXISTS',
    FOLLOW_NOT_FOUND: 'FOLLOW_NOT_FOUND',
    CANNOT_FOLLOW_SELF: 'CANNOT_FOLLOW_SELF',

    // Validation
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

    // Server
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR',
    EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
};

module.exports = ERROR_CODES;
