const ERROR_CODES = {
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INVALID_TOKEN: 'INVALID_TOKEN',

    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

    BOOK_NOT_FOUND: 'BOOK_NOT_FOUND',
    BOOK_ALREADY_EXISTS: 'BOOK_ALREADY_EXISTS',

    POST_NOT_FOUND: 'POST_NOT_FOUND',
    POST_ACCESS_DENIED: 'POST_ACCESS_DENIED',

    COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
    COMMENT_ACCESS_DENIED: 'COMMENT_ACCESS_DENIED',

    FAVORITE_ALREADY_EXISTS: 'FAVORITE_ALREADY_EXISTS',
    FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',

    FOLLOW_ALREADY_EXISTS: 'FOLLOW_ALREADY_EXISTS',
    FOLLOW_NOT_FOUND: 'FOLLOW_NOT_FOUND',
    CANNOT_FOLLOW_SELF: 'CANNOT_FOLLOW_SELF',

    VALIDATION_ERROR: 'VALIDATION_ERROR',
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR',
    EXTERNAL_API_ERROR: 'EXTERNAL_API_ERROR',
};

module.exports = ERROR_CODES;
